import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db,init,snapshot,encrypt,decrypt,getSettings,month} from '@/lib/store';
import {startJob,processJob} from '@/lib/engine';
import {verifyConnection} from '@/lib/providers';
import {brandMention,normalizeUrl,matchSite} from '@/lib/citations';
import {countries,type Provider,type Question,type Result,type Site} from '@/lib/model';
import {z} from 'zod';
import {manageCatalog} from '@/lib/catalog';
export const dynamic='force-dynamic';
const country=z.enum(['KR','US','CA','AU','CN','TW','JP','MN']);const provider=z.enum(['openai','claude','gemini']);
async function identity(){const user=await getChatGPTUser();if(!user)throw new Error('로그인이 필요합니다.');await init(user.userId);const owner=await db().prepare('SELECT value FROM config WHERE key=?').bind('owner').first<{value:string}>();const member=await db().prepare('SELECT role FROM members WHERE email=?').bind(user.email.toLowerCase()).first<{role:string}>();return {...user,role:user.userId==='password-admin'||owner?.value===user.userId?'admin':member?.role||'viewer'};}
function failure(e:unknown){const message=e instanceof z.ZodError?'입력값을 확인해 주세요. '+e.issues.map(i=>i.message).join(' '):(e as Error).message;const safe=/D1_|SQLITE|no such table|binding/i.test(message)?'저장소를 준비하지 못했습니다. 관리자에게 문의하거나 다시 시도하세요.':message;return Response.json({error:safe},{status:message.includes('로그인')?401:message.includes('권한')?403:400,headers:{'Cache-Control':'no-store'}});}
export async function GET(){try{const user=await identity();return Response.json(await snapshot(user.role),{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Error('다른 사이트에서 보낸 요청은 허용하지 않습니다.');if(!request.headers.get('content-type')?.includes('application/json'))throw new Error('JSON 요청만 지원합니다.');const raw=await request.text();if(raw.length>150000)throw new Error('입력 데이터가 너무 큽니다.');const user=await identity();const b=JSON.parse(raw);if(!['admin','editor'].includes(user.role))throw new Error('수정 권한이 없습니다.');const d=db();let result:unknown={ok:true};
 switch(b.action){
 case 'siteUpdate': case 'siteDelete': case 'siteRestore': case 'questionUpdate': case 'questionDelete': case 'questionRestore': result=await manageCatalog(d,b.action,b);break;
 case 'siteAdd':{const input=z.object({name:z.string().trim().min(1).max(80),domain:z.string().trim().min(3).max(300)}).parse(b);const url=normalizeUrl(input.domain.includes('://')?input.domain:`https://${input.domain}`);if(!url)throw new Error('유효한 웹사이트 주소를 입력하세요.');const host=new URL(url).hostname;if(!host.includes('.')||/^[\d.]+$/.test(host)||host.includes(':')||/\.(local|localhost|internal)$/.test(host))throw new Error('공개 도메인을 입력하세요.');const duplicate=await d.prepare('SELECT deleted FROM sites WHERE domain=?').bind(host).first<{deleted:number}>();if(duplicate)throw new Error(duplicate.deleted?'삭제 항목에 있는 주소입니다. 해당 사이트를 복원하세요.':'이미 등록된 사이트 주소입니다.');await d.prepare('INSERT INTO sites (id,name,domain,active) VALUES (?,?,?,1)').bind(crypto.randomUUID(),input.name,host).run();break;}
 case 'siteToggle':{const v=z.object({id:z.string(),active:z.boolean()}).parse(b);await d.prepare('UPDATE sites SET active=?,version=version+1 WHERE id=? AND deleted=0').bind(Number(v.active),v.id).run();break;}
 case 'questionAdd':{const q=z.object({text:z.string().trim().min(5).max(2000),keyword:z.string().trim().min(1).max(50),language:z.string().min(1).max(40),countries:z.array(country).min(1).max(8),branded:z.boolean()}).parse(b);const id=crypto.randomUUID();await d.prepare('INSERT INTO questions (id,payload) VALUES (?,?)').bind(id,JSON.stringify({...q,id,active:1,branded:Number(q.branded),version:1,countries:[...new Set(q.countries)]})).run();break;}
 case 'questionToggle':{const v=z.object({id:z.string(),active:z.boolean()}).parse(b);const q=await d.prepare('SELECT payload FROM questions WHERE id=?').bind(v.id).first<{payload:string}>();if(!q||JSON.parse(q.payload).deleted)throw new Error('질문을 찾을 수 없거나 삭제되었습니다.');await d.prepare('UPDATE questions SET payload=? WHERE id=?').bind(JSON.stringify({...JSON.parse(q.payload),active:Number(v.active)}),v.id).run();break;}
 case 'settings':{if(user.role!=='admin')throw new Error('관리자 권한이 필요합니다.');const s=z.object({enabled:z.boolean(),repeats:z.number().int().min(1).max(3),monthlyLimit:z.number().int().min(10).max(10000),countries:z.array(country).min(1).max(8),weekday:z.literal(1),hour:z.literal(9)}).parse(b.settings);await d.prepare('UPDATE config SET value=? WHERE key=?').bind(JSON.stringify(s),'settings').run();break;}
 case 'connection':{if(user.role!=='admin')throw new Error('관리자 권한이 필요합니다.');const c=z.object({provider,model:z.string().trim().min(1).max(100).regex(/^[a-zA-Z0-9._-]+$/),key:z.string().trim().max(1000),enabled:z.boolean()}).parse(b);const old=await d.prepare('SELECT secret,model FROM connections WHERE id=?').bind(c.provider).first<{secret:string;model:string}>();if(!c.key&&!old?.secret)throw new Error('API 키를 입력해 주세요.');const secret=c.key?await encrypt(c.key):old!.secret;await d.prepare('UPDATE connections SET model=?,secret=?,enabled=?,tested=NULL WHERE id=?').bind(c.model,secret,Number(c.enabled),c.provider).run();break;}
 case 'testConnection':{if(user.role!=='admin')throw new Error('관리자 권한이 필요합니다.');const p=provider.parse(b.provider);const c=await d.prepare('SELECT secret,model FROM connections WHERE id=?').bind(p).first<{secret:string;model:string}>();if(!c?.secret)throw new Error('먼저 API 키를 저장해 주세요.');if(p==='gemini'){const settings=await getSettings();await d.prepare('INSERT OR IGNORE INTO usage (month,count) VALUES (?,0)').bind(month()).run();const reserved=await d.prepare('UPDATE usage SET count=count+1 WHERE month=? AND count<?').bind(month(),settings.monthlyLimit).run();if(!reserved.meta.changes)throw new Error('월 실행 한도에 도달했습니다.');}await verifyConnection(p,await decrypt(c.secret),c.model);await d.prepare('UPDATE connections SET tested=? WHERE id=?').bind(new Date().toISOString(),p).run();result={message:p==='gemini'?'Gemini 답변 생성·웹 검색·출처 반환을 확인했습니다.':'저장된 키와 모델 접근 권한을 확인했습니다.'};break;}
 case 'start':result=await startJob(z.enum(['manual','weekly']).parse(b.kind));break;
 case 'process':result=await processJob();break;
 case 'observation':{const v=z.object({questionId:z.string(),provider,country,model:z.string().trim().min(1).max(100),answer:z.string().trim().min(1).max(50000),urls:z.string().max(15000),evidence:z.string().max(2000),countryMethod:z.enum(['미확인','접속 환경 확인','질문 시나리오']),createdAt:z.string().datetime()}).parse(b);if(v.countryMethod==='접속 환경 확인'&&!v.evidence.trim())throw new Error('접속 국가 확인 근거를 입력해 주세요.');if(new Date(v.createdAt).getTime()>Date.now()+300000)throw new Error('미래의 측정 시각을 입력할 수 없습니다.');const qr=await d.prepare('SELECT payload FROM questions WHERE id=?').bind(v.questionId).first<{payload:string}>();if(!qr)throw new Error('질문을 선택해 주세요.');const q=JSON.parse(qr.payload) as Question;if(q.deleted)throw new Error('삭제된 질문은 새 관측에 사용할 수 없습니다.');const sites=(await d.prepare('SELECT * FROM sites WHERE deleted=0').all()).results as Site[];const urls=[...new Set(v.urls.split(/\n/).map(x=>x.trim()).filter(Boolean))];const citations=urls.map(url=>{const n=normalizeUrl(url);if(!n)throw new Error('출처 URL 형식을 확인해 주세요.');return {url:n,title:'수동 확인 출처',text:'',siteId:matchSite(n,sites)};});const id=crypto.randomUUID(),jobId=crypto.randomUUID();const r:Result={...v,id,jobId,question:q.text,keyword:q.keyword,language:q.language,questionId:q.id,track:'manual',status:'success',citations,sites:[...new Set(citations.map(c=>c.siteId).filter(Boolean))] as string[],brand:brandMention(v.answer),error:null,signature:`manual:${q.id}:${q.version}:${v.provider}:${v.model}:${v.country}`,searchUsed:false,branded:q.branded};await d.batch([d.prepare("INSERT INTO jobs (id,slot,label,kind,status,created_at) VALUES (?,?,?,'observation','completed',?)").bind(jobId,jobId,'사용자 화면 관측',v.createdAt),d.prepare("INSERT INTO results (id,job_id,status,payload,created_at) VALUES (?,?,'success',?,?)").bind(id,jobId,JSON.stringify(r),v.createdAt)]);break;}
 default:throw new Error('지원하지 않는 작업입니다.');}
 // Audit contains action names only; API keys and request bodies are never logged.
 if(b.action!=='process')await d.prepare('INSERT INTO audit (id,actor,action,created_at) VALUES (?,?,?,?)').bind(crypto.randomUUID(),user.userId,String(b.action),new Date().toISOString()).run();return Response.json(result,{headers:{'Cache-Control':'no-store'}});
 }catch(e){return failure(e);}}
