import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=fs.readFileSync(new URL('../lib/citations.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
const {normalizeUrl,matchSite,brandMention,parseResponse}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const sites=[{id:'a',domain:'seoulvisionclinic.com',active:1},{id:'b',domain:'busanvisionclinic.com',active:1}];
assert.equal(normalizeUrl('https://WWW.seoulvisionclinic.com/a?utm_source=ai&id=3#x'),'https://seoulvisionclinic.com/a?id=3');
assert.equal(normalizeUrl('javascript:alert(1)'),null);
assert.equal(matchSite('https://seoulvisionclinic.com.evil.test/',sites),null);
assert.equal(matchSite('https://www.seoulvisionclinic.com/a',sites),'a');
assert.equal(brandMention('밝은 세상 안과 BGSS'),true);
const result=parseResponse('openai',{status:'completed',output:[{type:'web_search_call',status:'completed'},{type:'message',content:[{type:'output_text',text:'BGSS 답변',annotations:[{type:'url_citation',url:'https://seoulvisionclinic.com/a'},{type:'url_citation',url:'https://seoulvisionclinic.com/b'},{type:'url_citation',url:'https://busanvisionclinic.com/'}]}]}]},sites);
assert.deepEqual(result.sites,['a','b']);assert.equal(result.citations.length,3);assert.equal(result.searchUsed,true);
const noCitation=parseResponse('openai',{status:'completed',output:[{type:'web_search_call',status:'completed',sources:[{url:'https://seoulvisionclinic.com/'}]},{type:'message',content:[{type:'output_text',text:'BGSS 병원',annotations:[]}]}]},sites);
assert.equal(noCitation.sites.length,0);assert.equal(noCitation.brand,true);
assert.throws(()=>parseResponse('claude',{content:[{type:'web_search_tool_result',content:{type:'web_search_tool_result_error',error_code:'unavailable'}}]},sites));
assert.throws(()=>parseResponse('openai',{status:'incomplete',output:[]},sites));
const g=parseResponse('gemini',{candidates:[{finishReason:'STOP',content:{parts:[{text:'Test'}]},groundingMetadata:{webSearchQueries:['test'],groundingChunks:[{web:{uri:'https://seoulvisionclinic.com/a'}}],groundingSupports:[{segment:{text:'Test'},groundingChunkIndices:[0]}]}}]},sites);assert.deepEqual(g.sites,['a']);
const unused=parseResponse('gemini',{candidates:[{content:{parts:[{text:'No attribution'}]},groundingMetadata:{groundingChunks:[{web:{uri:'https://seoulvisionclinic.com/a'}}]}}]},sites);assert.equal(unused.sites.length,0);
console.log('PASS: URL normalization, unsafe links, host spoofing, brand-only, site deduplication, search-only exclusion, provider failure, truncated answers, Gemini support mapping.');
