'use client';
import {useState} from 'react';
import {Pencil,Trash2,RotateCcw,Plus} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Switch} from '@/components/ui/switch';
import {SiteForm,QuestionForm} from './forms';
import {toast} from 'sonner';
import type {Site,Question} from '@/lib/model';

export default function CatalogManager({kind,sites,questions,canEdit,onMutate}:{kind:'site'|'question';sites:Site[];questions:Question[];canEdit:boolean;onMutate:(action:string,body:Record<string,unknown>)=>Promise<unknown>}){
 const [trash,setTrash]=useState(false),[editing,setEditing]=useState<Site|Question|'new'|null>(null),[deleting,setDeleting]=useState<Site|Question|null>(null),[pending,setPending]=useState(false),[error,setError]=useState('');
 const isSite=kind==='site',label=isSite?'사이트':'질문',items=isSite?sites:questions,visible=items.filter(i=>!!i.deleted===trash),deletedCount=items.filter(i=>i.deleted).length;
 async function update(action:string,body:Record<string,unknown>){setPending(true);try{await onMutate(action,body);}finally{setPending(false);}}
 async function save(body:Record<string,unknown>){await update(kind+(editing==='new'?'Add':'Update'),body);setEditing(null);toast.success(`${label}을 저장했습니다.`);}
 return <div className="catalog-manager"><div className="section-heading"><div><h2>{isSite?'등록 사이트 관리':'모니터링 질문'}</h2><p>{items.filter(i=>!i.deleted).length}개 등록 · 수정 사항은 다음에 생성하는 측정부터 적용됩니다.</p></div><div className="catalog-toolbar"><button className="button secondary" aria-pressed={trash} onClick={()=>setTrash(v=>!v)}>{trash?'등록 목록 보기':`삭제 항목 (${deletedCount})`}</button>{canEdit&&!trash&&<button className="button primary" onClick={()=>setEditing('new')}><Plus size={16}/>{label} 추가</button>}</div></div>
 {trash&&<p className="catalog-hint">삭제한 항목은 새 측정에서 제외됩니다. 복원 후 활성 스위치를 켜면 다시 수집합니다.</p>}
 <Table><TableHeader><TableRow><TableHead>{label}</TableHead>{!isSite&&<><TableHead>키워드</TableHead><TableHead>언어 · 국가</TableHead><TableHead>버전</TableHead></>}<TableHead>{trash?'상태':'활성'}</TableHead><TableHead>관리</TableHead></TableRow></TableHeader><TableBody>{visible.map(item=><TableRow key={item.id}><TableCell className="question-cell">{isSite?<><strong>{(item as Site).name}</strong><small className="block">{(item as Site).domain}</small></>:(item as Question).text}</TableCell>{!isSite&&<><TableCell><span className="keyword-pill">{(item as Question).keyword}</span>{(item as Question).branded?<small className="block">브랜드 · KPI 제외</small>:null}</TableCell><TableCell>{(item as Question).language}<small className="block">{(item as Question).countries.join(', ')}</small></TableCell><TableCell>v{(item as Question).version}</TableCell></>}<TableCell>{trash?<span className="status-pill">삭제됨</span>:<Switch aria-label={`${isSite?(item as Site).name:(item as Question).text} 활성`} disabled={!canEdit||pending} checked={!!item.active} onCheckedChange={active=>void update(kind+'Toggle',{id:item.id,active}).catch(e=>toast.error(e.message))}/>}</TableCell><TableCell><div className="catalog-actions">{canEdit?(trash?<button className="button secondary" disabled={pending} onClick={()=>void update(kind+'Restore',{id:item.id}).then(()=>toast.success('복원했습니다. 활성 스위치를 켜면 수집에 포함됩니다.')).catch(e=>toast.error(e.message))}><RotateCcw size={15}/>복원</button>:<><button className="button secondary" disabled={pending} onClick={()=>setEditing(item)} aria-label={`${label} 수정`}><Pencil size={15}/>수정</button><button className="button catalog-delete" disabled={pending} onClick={()=>{setError('');setDeleting(item)}} aria-label={`${label} 삭제`}><Trash2 size={15}/>삭제</button></>):<span className="muted">조회 전용</span>}</div></TableCell></TableRow>)}</TableBody></Table>
 {!visible.length&&<div className="catalog-empty">{trash?'삭제한 항목이 없습니다.':`등록된 ${label}이 없습니다. 위의 추가 버튼으로 등록하세요.`}</div>}
 <Dialog open={!!editing} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{label} {editing==='new'?'추가':'수정'}</DialogTitle><DialogDescription>{isSite?'이름과 주소를 변경해도 기존 인용 기록은 유지됩니다.':'수정하면 질문 버전이 올라가며, 기존 답변은 당시의 질문 내용으로 보존됩니다.'}</DialogDescription></DialogHeader>{editing&&(isSite?<SiteForm key={editing==='new'?'new':editing.id} initial={editing==='new'?undefined:editing as Site} onSave={save}/>:<QuestionForm key={editing==='new'?'new':editing.id} initial={editing==='new'?undefined:editing as Question} onSave={save}/>)}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={open=>!open&&!pending&&setDeleting(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{label}을 삭제할까요?</AlertDialogTitle><AlertDialogDescription><span className="delete-item-name">{deleting&&(isSite?(deleting as Site).name:(deleting as Question).text)}</span>등록 목록과 이후 새 측정에서 제외됩니다. 과거 측정 결과는 보존되며, 삭제 항목에서 복원할 수 있습니다.</AlertDialogDescription></AlertDialogHeader>{error&&<p className="form-error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={pending}>취소</AlertDialogCancel><AlertDialogAction className="catalog-delete-confirm" disabled={pending} onClick={async e=>{e.preventDefault();if(!deleting)return;setError('');try{await update(kind+'Delete',{id:deleting.id});setDeleting(null);toast.success(`${label}을 삭제했습니다. 삭제 항목에서 복원할 수 있습니다.`);}catch(err){setError((err as Error).message);}}}>{pending?'삭제 중…':'삭제'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
