'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,ArrowUpRight,BarChart3,CalendarDays,ChevronRight,CircleHelp,Clock3,Download,Eye,FileText,Globe2,LayoutDashboard,Link2,Loader2,MessageSquareText,Play,Plus,RefreshCw,Search,Settings2,ShieldCheck,SlidersHorizontal} from 'lucide-react';
import {Sidebar,SidebarContent,SidebarFooter,SidebarHeader,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarProvider,SidebarTrigger} from '@/components/ui/sidebar';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Skeleton} from '@/components/ui/skeleton';
import {Progress} from '@/components/ui/progress';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer} from 'recharts';
import {countries,providers,emptyData,pct,displayDate,type DashboardData,type Result,type Settings} from '@/lib/model';
import {SettingsPanel,SiteForm,QuestionForm,ObservationForm,ConnectionForm} from './forms';
import {weeklyDelta} from '@/lib/metrics';
import CatalogManager from './catalog-manager';
async function api(action:string,data:Record<string,unknown>={}){const r=await fetch('/api/monitor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data})});const j=await r.json() as DashboardData & {error?:string;message?:string;jobId?:string;pending?:boolean};if(!r.ok)throw new Error(j.error||'요청을 완료하지 못했습니다.');return j;}
function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="filter-select"><SelectValue/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}
function EmptyChart({text='첫 측정이 완료되면 표시됩니다.'}:{text?:string}){return <div className="empty-chart"><BarChart3 size={28}/><span>{text}</span><small>미측정은 인용 0회와 다릅니다.</small></div>;}
function Heading({title,sub,action}:{title:string;sub?:string;action?:React.ReactNode}){return <div className="section-heading"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{action}</div>;}
const nav=[{id:'overview',label:'전체 대시보드',icon:LayoutDashboard},{id:'sites',label:'사이트 분석',icon:Globe2},{id:'questions',label:'질문 · 키워드',icon:MessageSquareText},{id:'results',label:'인용 상세',icon:FileText},{id:'schedule',label:'모니터링 일정',icon:CalendarDays},{id:'settings',label:'연결 · 설정',icon:Settings2}];
export default function Dashboard(){
const [data,setData]=useState<DashboardData>(emptyData),[loading,setLoading]=useState(true),[error,setError]=useState('');
const [page,setPage]=useState('overview'),[track,setTrack]=useState('api'),[country,setCountry]=useState('all'),[provider,setProvider]=useState('all'),[site,setSite]=useState('all'),[keyword,setKeyword]=useState('all'),[period,setPeriod]=useState('28'),[language,setLanguage]=useState('all'),[method,setMethod]=useState('all'),[query,setQuery]=useState('');
const [modal,setModal]=useState(''),[detail,setDetail]=useState<Result|null>(null),[busy,setBusy]=useState(false),[processing,setProcessing]=useState(false),[tablePage,setTablePage]=useState(0);
const load=useCallback(async()=>{try{const r=await fetch('/api/monitor',{cache:'no-store'});const j=await r.json() as DashboardData & {error?:string;message?:string;jobId?:string;pending?:boolean};if(!r.ok)throw new Error(j.error||'데이터를 불러오지 못했습니다.');setData(j);setError('');return j as DashboardData;}catch(e){setError((e as Error).message);return null;}finally{setLoading(false);}},[]);
useEffect(()=>{void load();const u=new URL(location.href);for(const [k,fn] of [['country',setCountry],['provider',setProvider],['site',setSite],['keyword',setKeyword],['track',setTrack],['period',setPeriod]] as const){const v=u.searchParams.get(k);if(v)fn(v);}},[load]);
useEffect(()=>{if(loading)return;const u=new URL(location.href);for(const [k,v] of Object.entries({country,provider,site,keyword,track,period}))v==='all'?u.searchParams.delete(k):u.searchParams.set(k,v);history.replaceState(null,'',u);setTablePage(0);},[country,provider,site,keyword,track,period,loading]);
const mutate=useCallback(async(action:string,body:Record<string,unknown>={})=>{setBusy(true);try{const r=await api(action,body);await load();return r;}finally{setBusy(false);}},[load]);
const run=useCallback(async(kind='manual')=>{try{const r=await mutate('start',{kind});if(r.message)toast(r.message);if(r.jobId){setProcessing(true);toast.success('측정을 시작합니다. 이 화면을 열어두세요.');}return r;}catch(e){toast.error((e as Error).message);return {error:(e as Error).message};}},[mutate]);
useEffect(()=>{if(!processing)return;let stop=false;const work=async()=>{try{for(let i=0;i<600&&!stop;i++){const r=await api('process');await load();if(r.pending)await new Promise(resolve=>setTimeout(resolve,1200));if(!r.pending){setProcessing(false);toast.success('측정이 종료되었습니다. 결과와 실패 내역을 확인하세요.');break;}}}catch(e){setProcessing(false);toast.error((e as Error).message);}};void work();return()=>{stop=true;};},[processing,load]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>unknown}}).modelContext;if(!context)return;const controller=new AbortController();for(const tool of [{name:'get_monitoring_status',description:'연결과 주간 측정 상태를 읽습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(input&&Object.keys(input as object).length)throw new Error('인수가 필요하지 않습니다.');const d=await load();return d?{connections:d.connections,jobs:d.jobs,nextRun:d.nextRun,settings:d.settings}:{error:'조회 실패'};}},{name:'run_due_weekly_monitoring',description:'주간 예정일이 지난 경우 정기 측정을 생성하고 화면에서 수집합니다. API 비용이 발생할 수 있습니다. 같은 주차는 중복 생성하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(input&&Object.keys(input as object).length)throw new Error('인수가 필요하지 않습니다.');return run('weekly');}}])try{void Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[load,run]);
const rows=useMemo(()=>data.results.filter(r=>r.track===track&&(country==='all'||r.country===country)&&(provider==='all'||r.provider===provider)&&(keyword==='all'||r.keyword===keyword)&&(language==='all'||r.language===language)&&(method==='all'||r.countryMethod===method)&&!r.branded&&(period==='all'||new Date(r.createdAt).getTime()>=Date.now()-Number(period)*86400000)),[data.results,track,country,provider,keyword,period,language,method]);
const valid=rows.filter(r=>r.status==='success');const isCited=(r:Result)=>site==='all'?r.sites.length>0:r.sites.includes(site);const cited=valid.filter(isCited),mentioned=valid.filter(r=>r.brand).length,questionCount=new Set(valid.map(r=>r.questionId)).size,coverage=new Set(cited.map(r=>r.questionId)).size;
const shown=rows.filter(r=>(site==='all'||r.sites.includes(site))&&(!query||`${r.question} ${r.answer} ${r.keyword}`.toLowerCase().includes(query.toLowerCase())));const available=data.connections.filter(c=>c.connected&&c.enabled).length;const canEdit=['admin','editor'].includes(data.role);const activeJob=data.jobs.find(j=>['running','queued'].includes(j.status));
const buckets=new Map<string,Record<string,number|string>>();for(const r of valid){const date=new Date(new Date(r.createdAt).getTime()+9*3600000).toISOString().slice(0,10);const b=buckets.get(date)||{date};b[`${r.provider}n`]=Number(b[`${r.provider}n`]||0)+1;b[`${r.provider}c`]=Number(b[`${r.provider}c`]||0)+(isCited(r)?1:0);buckets.set(date,b);}const trend=[...buckets.values()].sort((a,b)=>String(a.date).localeCompare(String(b.date))).map(b=>Object.fromEntries([['date',String(b.date).slice(5)],...providers.map(p=>[p.id,b[`${p.id}n`]?Number(b[`${p.id}c`])/Number(b[`${p.id}n`])*100:null])]));
function exportCsv(){const esc=(v:unknown)=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const lines=[['측정 시각','트랙','국가','국가판정','AI','모델','질문','키워드','상태','직접인용','인용URL','브랜드언급','오류'],...shown.map(r=>[r.createdAt,r.track,r.country,r.countryMethod,r.provider,r.model,r.question,r.keyword,r.status,isCited(r)?'예':'아니오',r.citations.map(c=>c.url).join(' | '),r.brand?'예':'아니오',r.error])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(l=>l.map(esc).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));a.download=`BGSS-인용-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);}
const save=async(action:string,body:Record<string,unknown>)=>{await mutate(action,body);setModal('');toast.success('저장했습니다.');};
const delta=weeklyDelta(rows,data.jobs,site);
const metric=[{label:'공식 사이트 인용률',value:pct(cited.length,valid.length),note:`인용 ${cited.length} / 유효 응답 ${valid.length}`,icon:Link2,primary:true},{label:'인용 응답 수',value:valid.length?String(cited.length):'—',note:'응답 단위 · 사이트 중복 제외',icon:MessageSquareText},{label:'브랜드 언급률',value:pct(mentioned,valid.length),note:`밝은세상안과 언급 ${mentioned}건`,icon:Eye},{label:'질문 커버리지',value:pct(coverage,questionCount),note:`인용 질문 ${coverage} / 측정 ${questionCount}`,icon:BarChart3},{label:'수집 완료율',value:pct(valid.length,rows.length),note:`정상 ${valid.length} / 계획 ${rows.length}`,icon:Activity}];
return <SidebarProvider style={{'--sidebar-width':'232px'} as React.CSSProperties}><Toaster richColors position="top-center"/><Sidebar className="app-sidebar"><SidebarHeader className="brand-header"><div className="brand-icon"><Eye size={23}/></div><div><strong>밝은세상안과</strong><span>AI VISIBILITY</span></div></SidebarHeader><SidebarContent><div className="nav-caption">WORKSPACE</div><SidebarMenu className="nav-items">{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={page===n.id} onClick={()=>setPage(n.id)} className="nav-item"><n.icon size={19}/><span>{n.label}</span>{n.id==='sites'&&<small>{data.sites.filter(s=>s.active).length}</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-schedule"><CalendarDays size={20}/><strong>주 1회 모니터링</strong><p>매주 {['일','월','화','수','목','금','토'][data.settings.weekday]}요일 · {data.settings.hour}:00 KST</p><span>{data.settings.enabled?'정기 측정 설정됨':'일시중지'}</span><button onClick={()=>setPage('schedule')}>일정 확인 <ChevronRight size={14}/></button></div></SidebarContent><SidebarFooter className="user-footer"><div className="avatar">BG</div><div><strong>마케팅 워크스페이스</strong><span>밝은세상안과 · 비공개</span></div><ShieldCheck size={16}/></SidebarFooter></Sidebar>
<main className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>마케팅 인사이트</span><ChevronRight size={14}/><strong>{nav.find(n=>n.id===page)?.label}</strong></div><div className="topbar-right"><span className="private-badge"><ShieldCheck size={14}/> 비공개 워크스페이스</span><button className="icon-button" aria-label="집계 기준" onClick={()=>setModal('help')}><CircleHelp size={20}/></button><div className="avatar small">BG</div></div></header><div className="page-content"><div className="page-title"><div><div className="eyebrow">WEEKLY AI MONITORING</div><h1>{page==='overview'?'AI 인용 대시보드':nav.find(n=>n.id===page)?.label}</h1><p>{page==='overview'?'우리의 정보가 AI의 답변에 어떻게 연결되는지 확인하세요.':'측정 조건과 근거를 함께 확인하고 관리하세요.'}</p></div><div className="title-actions"><button className="button secondary" onClick={exportCsv}><Download size={16}/> CSV 다운로드</button><button className="button primary" disabled={busy||processing||!canEdit} onClick={()=>setModal('run')}>{processing?<Loader2 className="spin" size={16}/>:<Play size={16}/>} {processing?'측정 진행 중':'지금 측정'}</button></div></div>
{error&&<div className="error-banner" role="alert"><span>{error}</span>{error.includes('로그인')?<a href="/signin-with-chatgpt?return_to=/" target="_top">로그인</a>:<button onClick={()=>void load()}>다시 시도</button>}</div>}
{!loading&&available===0&&page!=='settings'&&<div className="setup-banner"><div className="setup-icon"><Link2 size={21}/></div><div><strong>AI 서비스를 연결하면 첫 모니터링을 시작할 수 있어요.</strong><p>6개 사이트와 8개 국가가 준비되어 있습니다. 연결 전에는 실제 측정값이 표시되지 않습니다.</p></div><button onClick={()=>setPage('settings')}>AI 연결하기 <ArrowUpRight size={17}/></button></div>}
{activeJob&&<div className="job-banner"><Activity size={19}/><span>{activeJob.label} · {activeJob.done+activeJob.failed} / {activeJob.total} 처리</span><Progress value={(activeJob.done+activeJob.failed)/activeJob.total*100} className="job-progress"/>{!processing&&canEdit&&<button onClick={()=>setProcessing(true)}>수집 계속하기</button>}<small>이 화면을 열어두세요.</small></div>}
{['overview','sites','results'].includes(page)&&<><div className="data-toolbar"><Tabs value={track} onValueChange={setTrack}><TabsList className="track-tabs"><TabsTrigger value="api">API 정기 측정</TabsTrigger><TabsTrigger value="manual">사용자 화면 관측</TabsTrigger></TabsList></Tabs><span className="freshness"><Clock3 size={14}/>{data.jobs.find(j=>j.status==='completed')?`최근 완료 ${displayDate(data.jobs.find(j=>j.status==='completed')!.createdAt)}`:'첫 측정 대기 중'}</span></div><div className="filterbar"><SlidersHorizontal size={17}/><Picker label="기간" value={period} onChange={setPeriod} items={[{value:'7',label:'최근 7일'},{value:'28',label:'최근 4주'},{value:'90',label:'최근 90일'},{value:'all',label:'전체 기간'}]}/><Picker label="사이트" value={site} onChange={setSite} items={[{value:'all',label:'전체 사이트'},...data.sites.map(s=>({value:s.id,label:s.name+(s.deleted?' (삭제됨)':'')}))]}/><Picker label="AI" value={provider} onChange={setProvider} items={[{value:'all',label:'전체 AI 서비스'},...providers.map(p=>({value:p.id,label:track==='api'?p.name:p.screen}))]}/><Picker label="국가" value={country} onChange={setCountry} items={[{value:'all',label:'전체 국가'},...countries.map(c=>({value:c.code,label:c.name}))]}/><Picker label="키워드" value={keyword} onChange={setKeyword} items={[{value:'all',label:'전체 키워드'},...[...new Set(data.questions.map(q=>q.keyword))].map(k=>({value:k,label:k}))]}/><Picker label="언어" value={language} onChange={setLanguage} items={[{value:'all',label:'전체 언어'},...[...new Set(countries.map(c=>c.lang))].map(l=>({value:l,label:l}))]}/><Picker label="국가 판정 방식" value={method} onChange={setMethod} items={[{value:'all',label:'전체 국가 방식'},...['검색 위치 설정','질문 시나리오','접속 환경 확인','미확인'].map(l=>({value:l,label:l}))]}/><button className="reset" onClick={()=>{setCountry('all');setProvider('all');setSite('all');setKeyword('all');setQuery('');setLanguage('all');setMethod('all')}}><RefreshCw size={14}/> 초기화</button></div></>}
{page==='overview'&&<><div className="kpi-grid">{metric.map(m=><div className={`kpi-card ${m.primary?'featured':''}`} key={m.label}><div className="kpi-label">{m.label}<m.icon size={17}/></div>{loading?<Skeleton className="h-10 w-24 mt-5"/>:<div className="kpi-value">{m.value}</div>}<div className="kpi-note">{m.note}</div><div className="kpi-bottom">{m.primary&&delta?('전주 대비 '+(delta.points>=0?'+':'')+delta.points.toFixed(1)+'%p · n='+delta.n):valid.length?'비교 가능 표본 대기':'주간 측정 후 집계'}<span>↗</span></div></div>)}</div><div className="insight-strip"><span className="insight-label"><Activity size={16}/> 이번 주 체크</span><span>{available?`${available}개 AI 연결`:'AI 연결 대기'}</span><i/><span>{data.sites.filter(s=>s.active).length}개 사이트 추적</span><i/><span>{valid.length?`유효 응답 ${valid.length}개${valid.length<30?' · 표본 부족':''}`:'측정 데이터가 아직 없습니다.'}</span><button onClick={()=>setPage('schedule')}>다음 측정 {displayDate(data.nextRun)} <ChevronRight size={14}/></button></div><div className="chart-grid"><section className="panel trend-panel"><Heading title="인용률 추이" sub="측정일별 공식 사이트 인용률" action={<span className="mini-tag">주간 모니터링</span>}/><div className="chart-legend">{providers.map(p=><span key={p.id}><i style={{background:p.color}}/>{track==='api'?p.name:p.screen}</span>)}</div>{trend.length?<div className="line-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e6ebf1"/><XAxis dataKey="date" tickLine={false} axisLine={false} fontSize={12}/><YAxis domain={[0,100]} tickFormatter={v=>v+'%'} tickLine={false} axisLine={false} width={42} fontSize={12}/><Tooltip formatter={v=>[Number(v).toFixed(1)+'%']}/>{providers.map(p=><Line key={p.id} type="linear" dataKey={p.id} name={p.name} stroke={p.color} strokeWidth={2.5} dot={{r:4}} connectNulls={false}/>)}</LineChart></ResponsiveContainer></div>:<EmptyChart/>}<div className="panel-foot">같은 질문도 실행 시점과 검색 조건에 따라 답변이 달라질 수 있습니다.</div></section><section className="panel country-panel"><Heading title="국가별 AI 인용 현황" sub="검색 위치 설정 · 질문 시나리오 기준"/><div className="heatmap"><div className="heat-row head"><span>국가</span>{providers.map(p=><span key={p.id}>{p.screen}</span>)}</div>{countries.map(c=><div className="heat-row" key={c.code}><span><b>{c.code}</b>{c.name}</span>{providers.map(p=>{const v=valid.filter(r=>r.country===c.code&&r.provider===p.id),n=v.filter(isCited).length;return <button key={p.id} onClick={()=>{setCountry(c.code);setProvider(p.id);setPage('results')}} style={v.length?{background:`rgba(24,108,225,${.06+n/v.length*.5})`}:undefined} title={`${c.name} ${p.screen}: ${v.length}개 표본`}>{v.length?<>{pct(n,v.length)}<small>n={v.length}</small></>:'—'}</button>})}</div>)}</div><div className="panel-foot">— 미측정 · 실제 현지 접속을 증명하는 값은 아닙니다.</div></section></div></>}
{['overview','sites'].includes(page)&&<div className={page==='overview'?'chart-grid lower-grid':''}><section className="panel"><Heading title="사이트별 인용" sub="한 답변에서 같은 사이트는 1회로 집계" action={canEdit?<button className="text-button" onClick={()=>setModal('site')}><Plus size={15}/> 사이트 추가</button>:undefined}/><div className="site-list">{data.sites.filter(s=>!s.deleted).map((s,i)=>{const count=valid.filter(r=>r.sites.includes(s.id)).length;return <button key={s.id} className="site-row" onClick={()=>{setSite(s.id);setPage('results')}}><span className="site-number">{String(i+1).padStart(2,'0')}</span><div className="site-info"><strong>{s.name}{!s.active&&<small> 비활성</small>}</strong><span>{s.domain}</span></div><div className="site-bar"><i style={{width:`${valid.length?count/valid.length*100:0}%`}}/></div><span className="site-count">{valid.length?count:'—'}<small>회</small></span><span className="site-rate">{pct(count,valid.length)}</span><ChevronRight size={14}/></button>})}</div>{page==='sites'&&<CatalogManager kind="site" sites={data.sites} questions={data.questions} canEdit={canEdit} onMutate={mutate}/>}</section>{page==='overview'&&<section className="panel"><Heading title="키워드별 가시성" sub="질문 태그 기준 · 인용률과 표본 수" action={<button className="text-button" onClick={()=>setPage('questions')}>질문 관리 <ChevronRight size={14}/></button>}/><div className="keyword-list">{[...new Set(data.questions.map(q=>q.keyword))].slice(0,5).map((k,i)=>{const rs=valid.filter(r=>r.keyword===k);return <button className="keyword-row" key={k} onClick={()=>{setKeyword(k);setPage('results')}}><span className="keyword-icon">{String(i+1).padStart(2,'0')}</span><div><strong>{k}</strong><small>유효 응답 {rs.length}개</small></div><span>{pct(rs.filter(isCited).length,rs.length)}</span><ChevronRight size={14}/></button>})}{!data.questions.length&&<EmptyChart text="질문을 불러오는 중입니다."/>}</div><div className="keyword-note"><CircleHelp size={15}/><span>낮은 인용률의 질문에서 콘텐츠 개선 기회를 찾아보세요.</span></div></section>}</div>}
{page==='questions'&&<section className="panel"><CatalogManager kind="question" sites={data.sites} questions={data.questions} canEdit={canEdit} onMutate={mutate}/></section>}
{page==='results'&&<section className="panel"><Heading title="답변 및 인용 근거" sub={`${shown.length}개 응답 · 사이트 선택 시 해당 사이트의 인용 응답을 표시합니다.`} action={canEdit?<button className="button secondary" onClick={()=>setModal('observation')}><Plus size={16}/> 화면 관측 등록</button>:undefined}/><div className="table-search"><Search size={17}/><input aria-label="답변 검색" placeholder="질문, 키워드, 답변 검색" value={query} onChange={e=>{setQuery(e.target.value);setTablePage(0)}}/></div><Table><TableHeader><TableRow><TableHead>질문 · 키워드</TableHead><TableHead>AI 서비스</TableHead><TableHead>국가 · 방식</TableHead><TableHead>인용</TableHead><TableHead>측정 시각</TableHead><TableHead>상세</TableHead></TableRow></TableHeader><TableBody>{shown.slice(tablePage*15,tablePage*15+15).map(r=><TableRow key={r.id}><TableCell className="question-cell">{r.question}<small className="block">{r.keyword}</small></TableCell><TableCell>{providers.find(p=>p.id===r.provider)?.[track==='api'?'name':'screen']}<small className="block">{r.model}</small></TableCell><TableCell>{countries.find(c=>c.code===r.country)?.name}<small className="block">{r.countryMethod}</small></TableCell><TableCell><span className={`status-pill ${r.status==='success'&&isCited(r)?'success':''}`}>{r.status==='success'?(isCited(r)?`${r.sites.length}개 사이트`:'인용 0회'):r.status==='pending'?'대기':r.status==='running'?'수집 중':'수집 실패'}</span></TableCell><TableCell>{displayDate(r.createdAt)}</TableCell><TableCell><button className="icon-button" aria-label="답변 상세" onClick={()=>setDetail(r)}><ArrowUpRight size={18}/></button></TableCell></TableRow>)}</TableBody></Table>{!shown.length&&<EmptyChart text="선택한 조건의 측정 결과가 없습니다."/>}<div className="pagination"><span>{shown.length}개 중 {Math.min(tablePage*15+1,shown.length)}–{Math.min((tablePage+1)*15,shown.length)}</span><button disabled={!tablePage} onClick={()=>setTablePage(p=>p-1)}>이전</button><button disabled={(tablePage+1)*15>=shown.length} onClick={()=>setTablePage(p=>p+1)}>다음</button></div></section>}
{page==='schedule'&&<><div className="schedule-hero"><div className="calendar-icon"><CalendarDays size={36}/></div><div><span className="eyebrow">WEEKLY SCHEDULE · ASIA/SEOUL</span><h2>매주 {['일','월','화','수','목','금','토'][data.settings.weekday]}요일, {data.settings.hour<12?'오전':'오후'} {data.settings.hour%12||12}시</h2><p>다음 예정: {displayDate(data.nextRun)} · {data.settings.enabled?'활성':'일시중지'}</p></div><span className="status-pill">{data.scheduler}</span></div><section className="panel"><Heading title="주간 측정 설정" sub="한 주에 한 번 수집하며 같은 주차의 자동 측정은 중복 생성하지 않습니다."/><div className="schedule-run"><button className="button secondary" disabled={!canEdit||busy||processing} onClick={()=>void run('weekly')}>이번 주 정기 측정 실행</button></div><SettingsPanel settings={data.settings} disabled={!canEdit||busy} onSave={async(s:Settings)=>{await mutate('settings',{settings:s});toast.success('설정했습니다.');}}/><div className="info-box"><Clock3 size={19}/><p>주간 예약은 이 작업의 Codex 자동화가 실행합니다. 예약 시각에 PC와 Codex가 실행 가능한 상태여야 하며 로그인 세션이 필요합니다. 수동으로 시작한 측정은 완료까지 화면을 열어두세요. 중단된 작업은 이어서 수집할 수 있습니다.</p></div></section><section className="panel"><Heading title="측정 이력" sub="정기 측정과 수동 측정을 구분합니다."/>{data.jobs.length?data.jobs.map(j=><div className="history-row" key={j.id}><CalendarDays size={19}/><div><strong>{j.label}</strong><small>{displayDate(j.createdAt)} · {j.kind==='weekly'?'주간 정기':'수동 추가'}</small></div><span>정상 {j.done} · 실패 {j.failed} / {j.total}</span><span className="status-pill">{j.status==='completed'?'완료':j.status==='running'?'진행 중':j.status==='cancelled'?'중단':'대기'}</span></div>):<EmptyChart text="첫 주간 측정 이력이 여기에 기록됩니다."/>}</section></>}
{page==='settings'&&<><section className="panel"><Heading title="AI 서비스 연결" sub="API 키는 암호화하여 저장하며, 저장한 키는 다시 표시하지 않습니다."/><div className="connections">{providers.map(p=>{const c=data.connections.find(c=>c.id===p.id);return <div className="connection-card" key={p.id}><div className="provider-mark" style={{background:p.color}}>{p.mark}</div><h3>{p.name}</h3><span className={`status-pill ${c?.connected?'success':''}`}>{c?.connected?(c.enabled?'측정 사용 중':'키 저장됨 · 측정 꺼짐'):'연결 전'}</span><p>{c?.model||'모델을 설정해 주세요.'}</p><small>{c?.tested?`연결 확인 ${displayDate(c.tested)}`:'아직 연결을 검증하지 않았습니다.'}</small><button className="button secondary" disabled={data.role!=='admin'} onClick={()=>setModal(`connect:${p.id}`)}>{c?.connected?'연결 관리':'서비스 연결'}<ArrowUpRight size={15}/></button></div>})}</div><div className="info-box"><CircleHelp size={19}/><p>ChatGPT·Claude·Gemini 구독과 API 이용료는 별개입니다. API 결과는 사용자 화면 관측과 분리합니다. 키 자동 발급을 원하시면 Codex에서 OpenAI Developers 플러그인을 활성화해 주세요.</p></div></section><section className="panel"><Heading title="국가 측정 방식" sub="실제 적용한 조건을 결과에 함께 기록합니다."/><div className="method-grid"><div><strong>OpenAI · Claude API</strong><p>검색 위치 설정을 적용합니다. 실제 현지 IP 접속 결과는 아닙니다.</p></div><div><strong>Gemini API</strong><p>질문에 국가 시나리오를 반영합니다. 위치 설정 방식과 구분합니다.</p></div><div><strong>사용자 화면 관측</strong><p>답변·출처·접속 근거를 등록하고 API와 별도로 조회합니다.</p></div></div></section><section className="panel"><Heading title="이번 달 수집 사용량" sub="자동·수동 실행 모두 포함 · 최대 실행 횟수로 과다 사용을 제한합니다."/><div className="usage"><strong>{data.usedThisMonth}<small> / {data.settings.monthlyLimit}회</small></strong><Progress value={data.usedThisMonth/data.settings.monthlyLimit*100}/></div></section></>}
<footer className="page-footer"><span><Eye size={15}/> 밝은세상안과 AI Visibility</span><span>등록 질문의 표본 측정 · 전체 AI 이용자의 인용량이 아닙니다.</span><button onClick={()=>setModal('help')}>집계 기준 보기</button></footer></div></main>
<Dialog open={!!modal} onOpenChange={v=>!v&&setModal('')}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{modal==='site'?'사이트 추가':modal==='question'?'모니터링 질문 추가':modal==='observation'?'사용자 화면 관측 등록':modal.startsWith('connect:')?'AI 서비스 연결':modal==='run'?'지금 모니터링 시작':'집계 기준'}</DialogTitle><DialogDescription>{modal==='run'?'AI에 질문을 보내며 API 이용료가 발생할 수 있습니다.':'측정 조건과 저장 내용을 확인해 주세요.'}</DialogDescription></DialogHeader>{modal==='site'&&<SiteForm onSave={b=>save('siteAdd',b)}/>} {modal==='question'&&<QuestionForm onSave={b=>save('questionAdd',b)}/>} {modal==='observation'&&<ObservationForm questions={data.questions.filter(q=>!q.deleted)} onSave={b=>save('observation',b)}/>} {modal.startsWith('connect:')&&<ConnectionForm connection={data.connections.find(c=>c.id===modal.split(':')[1])!} onSave={b=>save('connection',b)} onTest={async b=>{const r=await mutate('testConnection',b);toast.success(r.message||'확인했습니다.');}}/>}{modal==='run'&&<div className="form-stack"><p>활성 질문 {data.questions.filter(q=>q.active).length}개 · AI {available}개 · 국가 {data.settings.countries.length}개 · 반복 {data.settings.repeats}회</p><div className="info-box">수집 중 화면을 열어두세요. 키가 없는 AI는 실행하지 않습니다. 월 실행 한도를 넘기면 새 작업을 시작하지 않습니다.</div><button className="button primary" disabled={!available||busy} onClick={()=>{setModal('');void run();}}>측정 시작</button>{!available&&<p className="form-error">{data.connections.some(c=>c.connected)?'키는 저장되어 있지만 측정 사용이 꺼져 있습니다. AI 서비스 연결 → 연결 관리에서 측정에 사용을 켜고 저장하세요.':'먼저 AI 서비스를 연결해 주세요.'}</p>}</div>}{modal==='help'&&<div className="help-copy"><p><strong>인용률</strong> = 사이트가 출처로 연결된 응답 ÷ 유효 응답. 같은 답변의 동일 사이트는 한 번만 셉니다.</p><p><strong>브랜드 언급</strong>은 사이트 인용과 별도입니다. 검색 목록에만 등장한 사이트는 인용에서 제외합니다.</p><p><strong>미측정과 오류</strong>는 인용 0회가 아닙니다. 실패는 인용률 분모에서 제외합니다.</p><p><strong>표본 30개 미만</strong>은 참고용입니다. 언어·위치 적용 방식이 다른 결과를 순수한 국가 효과로 해석하면 안 됩니다.</p><p>사이트 필터는 KPI 분모를 유지합니다. 인용 상세에서는 해당 사이트의 인용 응답만 표시합니다.</p></div>}</DialogContent></Dialog>
<Sheet open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>답변 및 인용 근거</SheetTitle><SheetDescription>{detail&&`${detail.model} · ${detail.country} · ${detail.countryMethod}`}</SheetDescription></SheetHeader>{detail&&<div className="detail-body"><span className="keyword-pill">{detail.keyword}</span><h3>{detail.question}</h3><small>{displayDate(detail.createdAt)} · 검색 {detail.searchUsed?'실행 확인':'미사용/미확인'}</small>{detail.error&&<div className="error-banner">{detail.error}</div>}<div className="answer-text">{detail.answer||'답변이 아직 없습니다.'}</div><h3>인용 출처 {detail.citations.length}개</h3>{detail.citations.map((c,i)=><div className="citation-card" key={i}><span className="mini-tag">{c.siteId?'등록 사이트':'외부 출처'}</span><a href={c.url} target="_blank" rel="noreferrer">{c.title||c.url}<ArrowUpRight size={15}/></a><small>{c.url}</small>{c.text&&<blockquote>{c.text}</blockquote>}</div>)}{detail.evidence&&<p>관측 근거: {detail.evidence}</p>}</div>}</SheetContent></Sheet></SidebarProvider>;
}


