'use client';
import {useState} from 'react';
import {countries,type Settings,type Question,type Connection,type Site} from '@/lib/model';
import {Switch} from '@/components/ui/switch';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
type Save=(body:Record<string,unknown>)=>Promise<void>;
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="w-full" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>;}
function Form({onSubmit,children,label='저장'}:{onSubmit:()=>Promise<void>;children:React.ReactNode;label?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <form className="form-stack" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);try{await onSubmit();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{children}{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?'처리 중…':label}</button></form>;}
function CountryChecks({value,onChange}:{value:string[];onChange:(v:string[])=>void}){return <div className="country-checks">{countries.map(c=><label key={c.code}><Checkbox checked={value.includes(c.code)} onCheckedChange={v=>onChange(v?[...value,c.code]:value.filter(x=>x!==c.code))}/>{c.name}</label>)}</div>;}
export function SiteForm({onSave,initial}:{onSave:Save;initial?:Site}){const [name,setName]=useState(initial?.name||''),[domain,setDomain]=useState(initial?.domain||'');return <Form onSubmit={()=>onSave({name,domain,...(initial?{id:initial.id,version:initial.version||1}:{})})}><label>사이트 이름<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="예: 밝은세상안과 일본"/></label><label>사이트 주소<input required value={domain} onChange={e=>setDomain(e.target.value)} placeholder="https://example.com"/></label><p className="muted">www 표기는 자동 정리됩니다. 하위 도메인은 별도로 등록하세요.</p></Form>;}
export function QuestionForm({onSave,initial}:{onSave:Save;initial?:Question}){const [text,setText]=useState(initial?.text||''),[keyword,setKeyword]=useState(initial?.keyword||'스마일라식'),[language,setLanguage]=useState(initial?.language||'한국어'),[cs,setCs]=useState(initial?.countries||['KR']),[branded,setBranded]=useState(!!initial?.branded);return <Form onSubmit={()=>onSave({text,keyword,language,countries:cs,branded,...(initial?{id:initial.id,version:initial.version}:{})})}><label>질문<textarea required maxLength={2000} value={text} onChange={e=>setText(e.target.value)} placeholder="스마일라식으로 유명한 병원이 어디 있나?"/></label><div className="form-columns"><label>키워드<input required maxLength={50} value={keyword} onChange={e=>setKeyword(e.target.value)}/></label><label>질문 언어<Choice label="언어" value={language} onChange={setLanguage} options={[...new Set(countries.map(c=>c.lang))].map(l=>({value:l,label:l}))}/></label></div><label>측정 대상 국가</label><CountryChecks value={cs} onChange={setCs}/><label className="check-row"><Checkbox checked={branded} onCheckedChange={v=>setBranded(!!v)}/> 병원명·URL을 포함한 질문 (기본 KPI 제외)</label></Form>;}
export function ConnectionForm({connection,onSave,onTest}:{connection:Connection;onSave:Save;onTest:Save}){const [key,setKey]=useState(''),[model,setModel]=useState(connection.model),[enabled,setEnabled]=useState(connection.connected?!!connection.enabled:true),[test,setTest]=useState('');return <Form onSubmit={()=>onSave({provider:connection.id,key,model,enabled})}><label>모델 ID<input required value={model} maxLength={100} onChange={e=>setModel(e.target.value)}/></label><label>API 키<input type="password" value={key} onChange={e=>setKey(e.target.value)} required={!connection.connected} autoComplete="new-password" placeholder={connection.connected?'변경할 때만 입력':'서비스에서 발급한 API 키'}/></label><label className="check-row"><Switch checked={enabled} onCheckedChange={setEnabled}/> 측정에 사용 (수동·정기 모두 적용)</label><p className="muted">{connection.id==='gemini'?'연결 확인 시 질문 1건으로 답변 생성·웹 검색·출처를 검사합니다. API 비용과 월 실행 수 1회가 발생하며 측정 통계에는 포함하지 않습니다.':'저장 후 연결 확인을 실행하세요. 모델 접근 권한을 확인하며 답변 수집은 하지 않습니다.'}</p><button className="button secondary" type="button" disabled={!connection.connected} onClick={async()=>{try{await onTest({provider:connection.id});setTest('저장된 키의 연결을 확인했습니다.');}catch(e){setTest((e as Error).message);}}}>저장된 연결 확인</button>{test&&<p role="status">{test}</p>}</Form>;}
export function SettingsPanel({settings,disabled,onSave}:{settings:Settings;disabled:boolean;onSave:(s:Settings)=>Promise<void>}){const [s,setS]=useState(settings);return <Form onSubmit={()=>onSave(s)} label="측정 설정 저장"><fieldset disabled={disabled} className="form-stack"><label className="check-row"><Switch checked={s.enabled} onCheckedChange={enabled=>setS({...s,enabled})}/> 주간 모니터링 활성</label><div className="form-columns"><label>질문별 반복 수<Choice label="반복" value={String(s.repeats)} onChange={v=>setS({...s,repeats:Number(v)})} options={[1,2,3].map(n=>({value:String(n),label:n+'회'}))}/></label><label>월 최대 실행 수<input type="number" min={10} max={10000} value={s.monthlyLimit} onChange={e=>setS({...s,monthlyLimit:Number(e.target.value)})}/></label></div><label>측정 국가</label><CountryChecks value={s.countries} onChange={cs=>setS({...s,countries:cs})}/><p className="muted">예약: 매주 월요일 오전 9시 KST. 요일·시간 변경은 이 Codex 작업에 요청해 주세요.</p></fieldset></Form>;}
