import {db,getSettings,decrypt,month} from './store';
import {collect} from './providers';
import type {Result,Question,Site,Provider} from './model';
export async function startJob(kind:string){const d=db(),s=await getSettings();if(kind==='weekly'&&!s.enabled)return {message:'주간 모니터링이 일시중지되어 있습니다.'};const running=await d.prepare("SELECT id FROM jobs WHERE status IN ('planning','running') LIMIT 1").first<{id:string}>();if(running)return {jobId:running.id,message:'진행 중인 측정을 이어갑니다.'};
 const now=new Date(),kst=new Date(now.getTime()+9*3600000);const days=(kst.getUTCDay()-s.weekday+7)%7;const scheduled=new Date(Date.UTC(kst.getUTCFullYear(),kst.getUTCMonth(),kst.getUTCDate()-days,s.hour)-9*3600000);if(scheduled>now)scheduled.setUTCDate(scheduled.getUTCDate()-7);const slot=kind==='weekly'?`weekly:${scheduled.toISOString().slice(0,10)}`:crypto.randomUUID();
 if(kind==='weekly'){const existing=await d.prepare('SELECT id FROM jobs WHERE slot=?').bind(slot).first();if(existing)return {message:'이번 주 정기 측정은 이미 완료되었습니다.'};}
 const cs=await d.prepare('SELECT id,model FROM connections WHERE enabled=1 AND secret IS NOT NULL').all<{id:Provider;model:string}>();if(!cs.results.length)throw new Error('먼저 AI 서비스 API 키를 연결해 주세요.');
 const qs=(await d.prepare('SELECT payload FROM questions').all<{payload:string}>()).results.map(v=>JSON.parse(v.payload) as Question).filter(q=>q.active);const tasks:Result[]=[];const jobId=crypto.randomUUID();for(const q of qs)for(const country of q.countries.filter(c=>s.countries.includes(c)))for(const c of cs.results)for(let repeat=0;repeat<s.repeats;repeat++){tasks.push({id:crypto.randomUUID(),jobId,questionId:q.id,question:q.text,keyword:q.keyword,language:q.language,provider:c.id,model:c.model,country,countryMethod:c.id==='gemini'?'질문 시나리오':'검색 위치 설정',track:'api',status:'pending',answer:'',citations:[],sites:[],brand:false,error:null,createdAt:now.toISOString(),signature:`${q.id}|v${q.version}|${country}|${q.language}|${c.id}|${c.model}|${repeat}|search-auto-v1`,searchUsed:false,evidence:'',branded:q.branded});}
 if(!tasks.length)throw new Error('활성 질문과 측정 국가 조합이 없습니다.');if(tasks.length>1500)throw new Error('한 번에 1,500회까지 실행할 수 있습니다. 질문이나 반복 수를 줄여 주세요.');const used=(await d.prepare('SELECT count FROM usage WHERE month=?').bind(month()).first<{count:number}>())?.count||0;if(used+tasks.length>s.monthlyLimit)throw new Error(`월 실행 한도가 부족합니다. 예정 ${tasks.length}회 / 남은 ${s.monthlyLimit-used}회. 국가·질문을 줄이거나 한도를 변경하세요.`);
 const label=`${kst.getUTCMonth()+1}월 ${kst.getUTCDate()}일 ${kind==='weekly'?'주간':'추가'} 모니터링`;
 try{const claim=await d.prepare("INSERT INTO jobs (id,slot,label,kind,status,created_at) SELECT ?,?,?,?,'planning',? WHERE NOT EXISTS (SELECT 1 FROM jobs WHERE status IN ('planning','running'))").bind(jobId,slot,label,kind,now.toISOString()).run();if(!claim.meta.changes)return {message:'다른 실행이 시작되었습니다. 새로고침 후 이어서 실행하세요.'};}catch{return {message:'이번 측정이 이미 생성되었습니다. 새로고침해 주세요.'};}
 try{for(let i=0;i<tasks.length;i+=50)await d.batch(tasks.slice(i,i+50).map(t=>d.prepare('INSERT INTO results (id,job_id,status,payload,created_at) VALUES (?,?,?,?,?)').bind(t.id,jobId,'pending',JSON.stringify(t),now.toISOString())));await d.prepare("UPDATE jobs SET status='running' WHERE id=?").bind(jobId).run();return {jobId,total:tasks.length};}catch(e){await d.prepare("UPDATE jobs SET status='cancelled' WHERE id=?").bind(jobId).run();throw e;}
}
export async function processJob(){const d=db(),s=await getSettings();const now=new Date().toISOString();
 // Recover expired leases without ever counting a retry as an additional response.
 await d.prepare("UPDATE results SET status=CASE WHEN attempts<3 THEN 'pending' ELSE 'failed' END, lease=NULL WHERE status='running' AND lease<?").bind(now).run();
 const job=await d.prepare("SELECT id FROM jobs WHERE status='running' ORDER BY created_at LIMIT 1").first<{id:string}>();if(!job)return {pending:false};
 const tasks=await d.prepare("SELECT id,payload,attempts FROM results WHERE job_id=? AND status='pending' ORDER BY id LIMIT 3").bind(job.id).all<{id:string;payload:string;attempts:number}>();const siteRows=(await d.prepare('SELECT * FROM sites WHERE active=1').all()).results as Site[];
 await Promise.all(tasks.results.map(async row=>{const lease=new Date(Date.now()+120000).toISOString();const claim=await d.prepare("UPDATE results SET status='running',lease=?,attempts=attempts+1 WHERE id=? AND status='pending'").bind(lease,row.id).run();if(!claim.meta.changes)return;const task=JSON.parse(row.payload) as Result;try{
  await d.prepare('INSERT OR IGNORE INTO usage (month,count) VALUES (?,0)').bind(month()).run();const reserved=await d.prepare('UPDATE usage SET count=count+1 WHERE month=? AND count<?').bind(month(),s.monthlyLimit).run();if(!reserved.meta.changes)throw new Error('월 실행 한도에 도달하여 수집을 중지했습니다.');
  const c=await d.prepare('SELECT secret,enabled FROM connections WHERE id=?').bind(task.provider).first<{secret:string;enabled:number}>();if(!c?.secret||!c.enabled)throw new Error('AI 연결이 해제되거나 비활성화되었습니다.');const result=await collect(task,await decrypt(c.secret),siteRows);const {raw,...value}=result;await d.prepare("UPDATE results SET status='success',payload=?,raw=?,lease=NULL WHERE id=? AND status='running' AND lease=?").bind(JSON.stringify({...task,...value,status:'success',error:null,createdAt:new Date().toISOString()}),raw,row.id,lease).run();
 }catch(e){const message=(e as Error).name==='TimeoutError'?'AI 응답 시간 초과':(e as Error).message;const retry=row.attempts<2&&(/429|50[0234]|시간 초과|Timeout|fetch failed/.test(message));const status=retry?'pending':'failed';await d.prepare('UPDATE results SET status=?,payload=?,lease=NULL WHERE id=? AND lease=?').bind(status,JSON.stringify({...task,status,error:message}),row.id,lease).run();}}));
 const left=await d.prepare("SELECT COUNT(*) AS n FROM results WHERE job_id=? AND status IN ('pending','running')").bind(job.id).first<{n:number}>();if(!left?.n)await d.prepare("UPDATE jobs SET status='completed' WHERE id=?").bind(job.id).run();return {pending:!!left?.n,jobId:job.id,remaining:left?.n||0};
}
