import {env} from '@/lib/runtime';
import {initialSites,initialSettings,nextWeekly,type Question,type Settings,type Result,type DashboardData} from './model';
import {seedQuestions} from './seeds';
import {defaultModels} from './providers';
export function db(){if(!env.DB)throw new Error('저장소를 사용할 수 없습니다. 잠시 후 다시 시도하세요.');return env.DB;}
export async function init(userId:string){const d=db();await d.prepare('INSERT OR IGNORE INTO config (key,value) VALUES (?,?)').bind('owner',userId).run();const marker=await d.prepare('SELECT value FROM config WHERE key=?').bind('seed-v1').first();if(marker)return;const ss=initialSites.map(s=>d.prepare('INSERT OR IGNORE INTO sites (id,name,domain,active) VALUES (?,?,?,?)').bind(s.id,s.name,s.domain,s.active));const qs=seedQuestions.map(q=>d.prepare('INSERT OR IGNORE INTO questions (id,payload) VALUES (?,?)').bind(q.id,JSON.stringify(q)));await d.batch([...ss,...qs,...Object.entries(defaultModels).map(([id,m])=>d.prepare('INSERT OR IGNORE INTO connections (id,model,enabled) VALUES (?,?,0)').bind(id,m)),d.prepare('INSERT OR IGNORE INTO config (key,value) VALUES (?,?)').bind('settings',JSON.stringify(initialSettings)),d.prepare('INSERT OR IGNORE INTO config (key,value) VALUES (?,?)').bind('seed-v1','1')]);}
export async function getSettings(){const r=await db().prepare('SELECT value FROM config WHERE key=?').bind('settings').first<{value:string}>();return r?JSON.parse(r.value) as Settings:initialSettings;}
export function month(){return new Date(Date.now()+9*3600000).toISOString().slice(0,7);}
export async function snapshot(role:string):Promise<DashboardData>{const d=db();const [s,q,c,r,j,st,u]=await Promise.all([d.prepare('SELECT * FROM sites ORDER BY id').all(),d.prepare('SELECT payload FROM questions ORDER BY id').all<{payload:string}>(),d.prepare('SELECT id,model,enabled,tested,CASE WHEN secret IS NOT NULL THEN 1 ELSE 0 END AS connected FROM connections').all(),d.prepare('SELECT payload,status FROM results ORDER BY created_at DESC').all<{payload:string;status:string}>(),d.prepare("SELECT j.id,j.label,j.kind,j.status,j.created_at AS createdAt,COUNT(r.id) AS total,SUM(CASE WHEN r.status='success' THEN 1 ELSE 0 END) AS done,SUM(CASE WHEN r.status='failed' THEN 1 ELSE 0 END) AS failed FROM jobs j LEFT JOIN results r ON r.job_id=j.id GROUP BY j.id ORDER BY j.created_at DESC").all(),getSettings(),d.prepare('SELECT count FROM usage WHERE month=?').bind(month()).first<{count:number}>()]);return {sites:s.results as DashboardData['sites'],questions:q.results.map(v=>JSON.parse(v.payload) as Question),connections:c.results.map(v=>({...v,connected:!!v.connected,status:v.connected?'키 저장됨':'연결 전'})) as DashboardData['connections'],results:r.results.map(v=>({...JSON.parse(v.payload),status:v.status})) as Result[],jobs:j.results as DashboardData['jobs'],settings:st,usedThisMonth:u?.count||0,nextRun:nextWeekly(st),role,scheduler:env.SCHEDULER_STATUS||'예약 연결 대기',storageReady:true};}
async function aes(){if(!env.APP_ENCRYPTION_KEY)throw new Error('암호화 설정이 준비되지 않았습니다. 관리자에게 문의하세요.');return crypto.subtle.importKey('raw',Uint8Array.from(atob(env.APP_ENCRYPTION_KEY),c=>c.charCodeAt(0)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encrypt(secret:string){const iv=crypto.getRandomValues(new Uint8Array(12));const value=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aes(),new TextEncoder().encode(secret));return btoa(String.fromCharCode(...iv))+'.'+btoa(String.fromCharCode(...new Uint8Array(value)));}
export async function decrypt(secret:string){const [a,b]=secret.split('.');const value=await crypto.subtle.decrypt({name:'AES-GCM',iv:Uint8Array.from(atob(a),c=>c.charCodeAt(0))},await aes(),Uint8Array.from(atob(b),c=>c.charCodeAt(0)));return new TextDecoder().decode(value);}
